# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FROM ryanyard/magenta:latest-jupyter
LABEL description="Magenta GPU Container w/ Jupyter Notebooks"

# Update packages
RUN apt-get update --fix-missing \
    && apt-get -y upgrade \
    && apt-get -y dist-upgrade

# Install dependencies
RUN apt-get -y install \
    libasound2-dev \
    libjack-dev \
    ffmpeg \
    libsndfile-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Activate Magenta Env
RUN echo "conda activate magenta" >> ~/.bashrc
SHELL ["conda", "run", "-n", "magenta", "/bin/bash", "-c"]

# Install other dependencies
RUN yes | pip install magenta ddsp
